name: myenv
channels:
  - conda-forge
  - pytorch
dependencies:
  - autoflake
  - black
  - pandas
  - cudatoolkit
  - flake8
  - isort
  - jupyter
  - matplotlib
  - numpy
  - pytest
  - python
  - pytorch
  - pyyaml
  - tensorboard
  - tqdm
