name: myenv
channels:
  - conda-forge
  - pytorch
dependencies:
  - autoflake
  - black
  - pandas
  - cudatoolkit
  - flake8
  - isort
  - jupyter
  - matplotlib
  - numpy
  - pip
  - pip:
    - torchtestcase
    - -e .  # install package in development mode
    - umnn
  - pytest
  - python
  - pytorch
  - pyyaml
  - tensorboard
  - tqdm
